version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
